### ISSUE TITLE
Improve handling of corrupted param files

### ISSUE THREAD

**Issue by gmale** [zcash/zcash-android-wallet-sdk#201]
The Unstoppable Wallet reported the following crash and the problem was resolved by clearing the app's cache. This troubleshooting step could be done automatically by the SDK or at least facilitated so that it's easier.

```
PendingTransactionEntity(
    id=3,
    toAddress=[..],
    value=[..],
    memo=[..],
    accountIndex=0,
    minedHeight=-1,
    expiryHeight=-1,
    cancelled=0,
    encodeAttempts=1,
    submitAttempts=-1,
    errorMessage=failed to encode transaction due to : Sapling spend parameter file is not correct, please clean your ~/.zcash-params/ and re-run fetch-params. caused by: null,
    errorCode=2000,
    createTime=1610626473645,
    raw=[],
    rawTransactionId=[]
)
```

There are a few things we can do to improve this:

- [ ] #202 : Explicitly test what happens when params are downloaded and there is not enough disk space on the device
- [x] #204 : Add a function for clearing the param files
- [ ] #205 : Add a function for checksuming the param files
- [ ] #203 : Ensure expected behavior for downloading param files

**Comment by herou** [comment]
@gmale For the point: add a function for clearing the param files, assign it to me when you are done creating the tickets.
