### ISSUE TITLE
Android Transaction Handling Epic

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet-sdk#59]
As a mobile wallet developer I need an Android library that handles various types of zcash transactions so that I can easily integrate zcash into my wallet and interact with a majority of the existing zcash ecosystem.

Criteria:
- [x] Create, send, and receive Sapling z-address to Sapling z-address
- [x] Receive to a t-address
- [x] Send from a t-address to a Sapling z-address
- [x] Send from a Sapling z-address to a t-address
- [x] The state of transactions is clearly surfaced for developers (#64, #61, #62, #63)

For all of the above:
1) The developer can create the transaction by passing the recipient address and amount
2) The transaction can be broadcast to the zcash network
3) Documentation on how to create and broadcast the transaction exists
